services:
  server:
    build:
      context: ..
      dockerfile: ./packages/server/dockerfile
      target: development
    env_file: '../.env'
    networks:
      - local
    volumes:
      - type: bind
        source: ../packages/server
        target: /d-zone/packages/server

  web:
    build:
      context: ..
      dockerfile: ./packages/web/dockerfile
      target: development
    env_file: '../.env'
    networks:
      - local
    volumes:
      - type: bind
        source: ../packages/web
        target: /d-zone/packages/web
      - /d-zone/packages/web/.next

  caddy:
    image: caddy:latest
    networks:
      - local
    ports:
      - '3500:3500'
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
      - /data
      - /config

networks:
  local:
    driver: bridge
